// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKpsEljm16RQOtb5KXc_RSAYL4Pyz1IEU',
    appId: '1:52858438380:web:82d002a891d2b88a88dbc9',
    messagingSenderId: '52858438380',
    projectId: 'mycommerceflutter',
    authDomain: 'mycommerceflutter.firebaseapp.com',
    storageBucket: 'mycommerceflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kmoKvp-ZFZVL1CbDczRVWbubSrSLPjY',
    appId: '1:52858438380:android:86b3832dab61c86788dbc9',
    messagingSenderId: '52858438380',
    projectId: 'mycommerceflutter',
    storageBucket: 'mycommerceflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTI-sW_2DD3h2KTZxrHBHPadc3j0TRRY4',
    appId: '1:52858438380:ios:5c15fee8812e28b288dbc9',
    messagingSenderId: '52858438380',
    projectId: 'mycommerceflutter',
    storageBucket: 'mycommerceflutter.appspot.com',
    iosBundleId: 'dev.csuzarte.mycommerce.mycommerce',
  );
}
